"use client";
import { useEffect, useState } from "react";
import Image from "next/image";
import { archive, featuredProjects, type Project } from "@/data/projects";

const links = { github: "https://github.com/Aarsh-collab", linkedin: "https://linkedin.com/in/aarshdeep-singh-nandra-79b1042a3", email: "mailto:aarsh.singh2020@gmail.com" };
export default function Home() {
  const [caseStudy, setCaseStudy] = useState<Project | null>(null);
  const [filter, setFilter] = useState("All");
  const [scrollProgress, setScrollProgress] = useState(0);
  const filters = ["All", "AI / ML", "Research", "Full Stack", "Simulation", "Data", "Systems"];
  const projects = filter === "All" ? archive : archive.filter((p) => p[2].includes(filter));
  useEffect(() => {
    document.documentElement.classList.add("motion-ready");
    const sections = document.querySelectorAll<HTMLElement>("[data-reveal]");
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("is-visible"));
    }, { threshold: 0.12 });
    sections.forEach((section) => observer.observe(section));
    const updateProgress = () => {
      const max = document.documentElement.scrollHeight - window.innerHeight;
      setScrollProgress(max > 0 ? window.scrollY / max : 0);
    };
    updateProgress();
    window.addEventListener("scroll", updateProgress, { passive: true });
    return () => { observer.disconnect(); window.removeEventListener("scroll", updateProgress); document.documentElement.classList.remove("motion-ready"); };
  }, []);
  return <main>
    <div className="scroll-progress" aria-hidden="true"><span style={{ transform: `scaleX(${scrollProgress})` }} /></div>
    <nav><a className="mark" href="#top">AN<span>.</span></a><div className="nav-links"><a href="#work">Work</a><a href="#research">Research</a><a href="#about">About</a><a href="#contact">Contact</a></div><a className="resume" href="/resume.pdf">Resume ↗</a></nav>
    <section id="top" className="hero wrap hero-reveal" data-reveal><div className="hero-copy"><p className="eyebrow">Tempe, Arizona · Mathematics (Statistics) @ ASU</p><h1>Aarsh<br />Nandra<span>.</span></h1><p className="role">Applied AI Engineer<br />&amp; Researcher</p><p className="intro">I build AI systems, research infrastructure, and intelligent products—from multi-agent simulations and multimodal evaluation systems to full-stack AI applications.</p><div className="actions"><a className="primary" href="#work">View my work →</a><a className="secondary" href={links.email}>Get in touch</a></div></div><SystemMap /></section>
    <section id="work" className="wrap section" data-reveal><div className="heading"><div><p className="eyebrow">Selected work</p><h2>Things I&apos;ve made<br />work in the real world.</h2></div><p>Five projects at the intersection of applied AI, research engineering, and product systems.</p></div><div className="cards">{featuredProjects.map((p, i) => <article className={`card c${i}`} key={p.title}><div className="meta"><span>{p.category}</span><small>{p.status}</small></div><div><h3>{p.title}</h3><p>{p.summary}</p></div><footer><div>{p.tags.slice(0, 3).map((tag) => <i key={tag}>{tag}</i>)}</div><button onClick={() => setCaseStudy(p)}>Case study →</button></footer></article>)}</div></section>
    <section id="research" className="research" data-reveal><div className="wrap research-grid"><div><p className="eyebrow">Research</p><h2>Research is where I learn to ask better technical questions.</h2></div><div><p className="big">At ASU&apos;s DaRL Lab, I work on educational AI evaluation infrastructure and the emerging problem of multi-agent classroom simulation—taking seriously both what a system does and how we know it works.</p><div className="notes"><div><b>EduCAST</b><p>Co-first author; AAAI manuscript in preparation. Multimodal evaluation pipelines for personalized educational-video generation.</p></div><div><b>Classroom simulation</b><p>Ongoing Concordia-based research into teacher-student interaction, interventions, and emergent patterns.</p></div></div></div></div></section>
    <section className="wrap section experience" data-reveal><p className="eyebrow">Engineering experience</p>{[["Aug 2026 — present","Applied AI Engineer","ASU Next Lab","Voice-first mobile AI prototype for dementia-caregiving research."],["Apr 2026 — present","Undergraduate Researcher","DaRL Lab · ASU","Multimodal evaluation and research infrastructure for educational AI."],["Feb 2025 — Jan 2026","AI Systems Engineer","Ender-IT","Recruiter-facing matching and workflow infrastructure."]].map((x) => <div className="job" key={x[1]}><time>{x[0]}</time><h3>{x[1]} <em>{x[2]}</em></h3><p>{x[3]}</p></div>)}</section>
    <section className="wrap section archive" data-reveal><div className="archive-head"><div><p className="eyebrow">Project archive</p><h2>More systems, experiments, and prototypes.</h2></div><div className="filters">{filters.map((x) => <button className={filter === x ? "on" : ""} onClick={() => setFilter(x)} key={x}>{x}</button>)}</div></div><div className="list">{projects.map((p) => <article key={p[0]}><div><h3>{p[0]}</h3><p>{p[1]}</p></div><div><span>{p[2]}</span>{p[3] ? <a href={p[3]} target="_blank" rel="noreferrer">GitHub ↗</a> : <small>Internal deployment</small>}</div></article>)}</div></section>
    <section className="wrap toolkit" data-reveal><div><p className="eyebrow">Technical toolkit</p><h2>Useful tools,<br />organized by the work.</h2></div><div className="tools">{[["AI & ML","LLM systems · multimodal AI · RAG · embeddings · vector search · Whisper · scikit-learn"],["Research & evaluation","experimental design · benchmarking · human evaluation · ablations · agent-based simulation · statistics"],["Product & backend","Python · FastAPI · REST APIs · SQLAlchemy · document processing · rate limiting"],["Frontend & mobile","React · React Native · Expo · TypeScript · Vite · Tailwind CSS"],["Data & infrastructure","SQL · PostgreSQL · Supabase · pandas · NumPy · synthetic datasets"],["Core languages","Python · JavaScript · TypeScript · Java · SQL"]].map((x) => <div key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></section>
    <section id="about" className="about" data-reveal><div className="wrap about-grid"><p className="eyebrow">About</p><div><h2>I like making complicated things concrete.</h2><p>I&apos;m a Mathematics (Statistics) student at Arizona State University&apos;s Barrett, The Honors College. I work across AI research and engineering because I enjoy understanding complex systems: how they behave, how they can be evaluated, and how to turn an ambiguous idea into software people can use.</p><p>I&apos;m especially interested in intelligent systems, simulation, machine learning, and difficult technical problems that reward careful reasoning.</p></div></div></section>
    <footer id="contact" data-reveal><div className="wrap"><p className="eyebrow">Contact</p><h2>Let&apos;s make something<br />worth testing.</h2><a className="email" href={links.email}>aarsh.singh2020@gmail.com →</a><div className="bottom"><span>© {new Date().getFullYear()} Aarsh Nandra</span><div><a href={links.github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={links.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={links.email}>Email ↗</a></div></div></div></footer>
    {caseStudy && <div className="overlay" onMouseDown={() => setCaseStudy(null)}><article className={`modal ${caseStudy.demo ? "modal-featured" : ""}`} role="dialog" aria-modal="true" aria-labelledby="case-title" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={() => setCaseStudy(null)} aria-label="Close case study">×</button><p className="eyebrow">{caseStudy.category} · {caseStudy.status}</p><h2 id="case-title">{caseStudy.title}</h2><p className="lead">{caseStudy.summary}</p>{caseStudy.demo ? <FeaturedCaseStudy project={caseStudy} /> : <><div className="case-grid">{[["Context",caseStudy.detail.context],["What I built",caseStudy.detail.built],["Technical decisions",caseStudy.detail.decisions],["Current status",caseStudy.detail.status]].map((x) => <div key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div>{caseStudy.github && <a className="primary" href={caseStudy.github} target="_blank" rel="noreferrer">Open GitHub ↗</a>}</>}</article></div>}
  </main>;
}
function SystemMap(){return <div className="map"><div><span>Working set</span><span>2025—now</span></div><svg viewBox="0 0 500 380" role="img" aria-label="Connected map of AI products, agents, evaluation, and research"><path d="M75 100c118 0 81 90 175 90s99-98 178-98M250 190c-97 0-65 103-175 103m175-103c100 0 91 110 181 110"/><path className="dash" d="M75 100c70 75 115 57 175 90M428 92c-77 48-95 67-178 98M75 293c76-77 105-70 175-103m181 110c-72-91-101-72-181-110"/><circle cx="250" cy="190" r="40" className="core"/><circle cx="75" cy="100" r="27"/><circle cx="428" cy="92" r="27"/><circle cx="75" cy="293" r="27"/><circle cx="431" cy="300" r="27"/><text x="250" y="185">BUILD</text><text x="250" y="201">SYSTEMS</text><text x="75" y="96">AI / ML</text><text x="75" y="112">PRODUCTS</text><text x="428" y="88">MULTI-</text><text x="428" y="104">AGENTS</text><text x="75" y="289">RESEARCH</text><text x="75" y="305">SYSTEMS</text><text x="431" y="296">EVALUATION</text><text x="431" y="312">&amp; DATA</text></svg><p>A practice built around ambiguous problems, rigorous evaluation, and working software.</p></div>}
function FeaturedCaseStudy({ project }: { project: Project }) {
  if (!project.demo) return null;
  return <>
    <div className="case-actions"><a className="primary" href={project.live} target="_blank" rel="noreferrer">Open live product ↗</a><a className="secondary case-secondary" href={project.github} target="_blank" rel="noreferrer">View source ↗</a></div>
    <section className="demo-block"><div className="demo-block-head"><div><p className="eyebrow">Product walkthrough</p><h3>The complete workflow, in context.</h3></div><a href={`https://www.youtube.com/watch?v=${project.demo.youtubeId}`} target="_blank" rel="noreferrer">Watch on YouTube ↗</a></div><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${project.demo.youtubeId}`} title="InsuranceAI product walkthrough" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div></section>
    <section className="case-story"><div><p className="eyebrow">The product</p><p>{project.detail.context}</p></div><div><p className="eyebrow">What I built</p><p>{project.detail.built}</p></div><div><p className="eyebrow">Built deliberately</p><p>{project.detail.decisions}</p></div></section>
    <section className="case-gallery"><div className="demo-block-head"><div><p className="eyebrow">Product evidence</p><h3>One flow, from visitor to broker.</h3></div><p>Demo uses fictional applicant details.</p></div><div className="gallery-grid">{project.demo.gallery.map((shot, index) => <figure className={`gallery-shot shot-${index + 1}`} key={shot.src}><div className="shot-image"><Image src={shot.src} alt={shot.alt} fill sizes={index === 0 ? "(max-width: 800px) 100vw, 60vw" : "(max-width: 800px) 100vw, 40vw"} /></div><figcaption><span>{shot.label}</span><p>{shot.description}</p></figcaption></figure>)}</div></section>
    <p className="case-disclaimer">{project.detail.status}</p>
  </>;
}
